/**
 * Global API injected into MotionCam JavaScript automation sessions.
 *
 * Scripts run inside MotionCam's embedded QuickJS runtime. The API is available
 * as `globalThis.motioncam` and `globalThis.console`.
 */
declare global {
  const motioncam: MotionCamApi;

  type MotionCamCaptureMode =
    | 'ZSL'
    | 'BURST'
    | 'RAW_VIDEO'
    | 'LOG_VIDEO'
    | 'TIMELAPSE';

  interface MotionCamApi {
    /** Latest runtime state snapshot. Reading this property asks the app for fresh state. */
    readonly state: MotionCamState;

    /** Camera control and camera state helpers. */
    readonly camera: MotionCamCameraApi;

    /** Capture mode and start/stop helpers. */
    readonly capture: MotionCamCaptureApi;

    /** Discovered cameras and static control ranges. Reading this property asks the app for fresh data. */
    readonly cameras: MotionCamCameraInfo[];

    /** User-facing lens profiles. Reading this property asks the app for fresh data. */
    readonly profiles: MotionCamProfileInfo[];

    /** User-facing lens catalog. Reading this property asks the app for fresh data. */
    readonly lenses: MotionCamLensInfo[];

    /** Console sink connected to the MotionCam automation console. */
    readonly console: MotionCamConsoleApi;

    /** Returns the same state snapshot as `motioncam.state`. */
    getState(): MotionCamState;

    /** Returns the same camera list as `motioncam.cameras`. */
    getCameras(): MotionCamCameraInfo[];

    /** Returns the same lens catalog as `motioncam.lenses`. */
    getLenses(): MotionCamLensInfo[];

    /** Returns the same profile list as `motioncam.profiles`. */
    getProfiles(): MotionCamProfileInfo[];

    /** Selects an available lens profile and restarts the camera if required. */
    selectProfile(profileId: string): void;
  }

  interface MotionCamState {
    schemaVersion: number;
    version: number;
    timestampMs: number;
    app: MotionCamAppState;
    camera: MotionCamCameraState;
    recording: MotionCamRecordingState;
  }

  interface MotionCamAppState {
    captureMode: MotionCamCaptureMode;
  }

  interface MotionCamCameraState {
    id: string | null;
    lensId: string | null;
    profileId: string | null;
    controllerState: string;
    ready: boolean;
    running: boolean;
    previewRunning: boolean;
    controls: MotionCamCameraControlsState;
  }

  interface MotionCamCameraControlsState {
    focus: MotionCamFocusState;
    exposure: MotionCamExposureState;
    whiteBalance: MotionCamWhiteBalanceState;
  }

  interface MotionCamFocusState {
    manual: boolean;
    distanceDiopters: number;
  }

  interface MotionCamExposureState {
    isoManual: boolean;
    iso: number;
    shutterManual: boolean;
    shutterNs: number;
  }

  interface MotionCamWhiteBalanceState {
    manual: boolean;
    temperature: number;
    tint: number;
  }

  interface MotionCamRecordingState {
    active: boolean;
    state: string;
    finalizing: boolean;
  }

  interface MotionCamCameraInfo {
    id: string;
    physicalCameraId: string | null;
    active: boolean;
    logical: boolean;
    frontFacing: boolean;
    requiresJavaBackend: boolean;
    sensorOrientation: number | null;
    isoRange: number[] | null;
    exposureTimeRangeNs: number[] | null;
    focalLengths: number[] | null;
    apertures: number[] | null;
    minFocusDistance: number | null;
    maxFocusDistance: number | null;
    hyperFocalDistance: number | null;
    oisSupported: boolean | null;
    zoomRange: number[] | null;
    exposureCompensationRange: number[] | null;
    exposureCompensationStep: number[] | null;
    fpsRange: number[] | null;
  }

  interface MotionCamProfileInfo {
    id: string;
    lensId: string;
    cameraId: string;
    name: string;
    active: boolean;
    default: boolean;
    autoGenerated: boolean;
  }

  interface MotionCamLensInfo {
    id: string;
    label: string;
    buttonPrimaryLabel: string;
    buttonSecondaryLabel: string | null;
    frontFacing: boolean;
    fallbackCameraId: string;
    focalLengthMm: number;
    active: boolean;
    defaultProfileId: string | null;
    activeProfileId: string | null;
    profiles: MotionCamProfileInfo[];
  }

  interface MotionCamCameraApi {
    readonly iso: number;
    readonly shutterNs: number;
    readonly focusDistance: number;
    readonly manualFocusEnabled: boolean;
    readonly whiteBalance: MotionCamWhiteBalanceState;

    setIso(iso: number): void;
    setShutterNs(shutterNs: number): void;
    setFocusDistance(diopters: number): void;
    setWhiteBalance(temperature: number, tint: number): void;

    setExposureLock(enabled: boolean): void;
    setIsoLock(enabled: boolean): void;
    setShutterLock(enabled: boolean): void;
    setFocusLock(enabled: boolean): void;
    setAutoWhiteBalanceLock(enabled: boolean): void;
    toggleAutoWhiteBalanceLock(): void;

    setIsoAuto(): void;
    setShutterAuto(): void;
    setFocusAuto(): void;
    setWhiteBalanceAuto(): void;
    resetManual(): void;
  }

  interface MotionCamCaptureApi {
    readonly modes: MotionCamCaptureModeConstants;
    setMode(mode: MotionCamCaptureMode): void;
    start(): void;
    stop(): void;
  }

  interface MotionCamCaptureModeConstants {
    readonly ZSL: 'ZSL';
    readonly BURST: 'BURST';
    readonly RAW_VIDEO: 'RAW_VIDEO';
    readonly LOG_VIDEO: 'LOG_VIDEO';
    readonly TIMELAPSE: 'TIMELAPSE';
  }

  interface MotionCamConsoleApi {
    log(...values: unknown[]): void;
    warn(...values: unknown[]): void;
    error(...values: unknown[]): void;
    clear(): void;
  }
}

export {};
