package com.motioncam.remote_labs.remote

import org.json.JSONArray
import org.json.JSONObject

data class MotionCamError(
    val code: String,
    val message: String,
)

data class AuthResult(
    val protocolVersion: Int,
    val authMode: String,
    val serverName: String,
    val clientName: String,
    val capabilities: List<String>,
)

data class CameraState(
    val cameraId: String = "-",
    val lensId: String? = null,
    val profileId: String? = null,
    val captureMode: String = "-",
    val controllerState: String = "-",
    val cameraReady: Boolean = false,
    val cameraRunning: Boolean = false,
    val previewRunning: Boolean = false,
    val recordingActive: Boolean = false,
    val recordingState: String = "-",
    val recordingFinalizing: Boolean = false,
    val isoManual: Boolean? = null,
    val iso: Int? = null,
    val shutterManual: Boolean? = null,
    val shutterNs: Long? = null,
    val manualFocusEnabled: Boolean? = null,
    val focusDistance: Double? = null,
    val whiteBalanceManual: Boolean? = null,
    val whiteBalanceTemperature: Int? = null,
    val whiteBalanceTint: Int? = null,
) {
    companion object {
        fun fromJson(json: JSONObject): CameraState {
            val camera = json.optJSONObject("camera")
            val controls = camera?.optJSONObject("controls")
            val exposure = controls?.optJSONObject("exposure")
            val focus = controls?.optJSONObject("focus")
            val whiteBalanceControls = controls?.optJSONObject("whiteBalance")
            val legacyWhiteBalance = camera?.optJSONObject("whiteBalance")
            val app = json.optJSONObject("app")
            val recording = json.optJSONObject("recording")
            return CameraState(
                cameraId = camera?.optNullableString("id") ?: json.optString("cameraId", "-"),
                lensId = camera?.optNullableString("lensId"),
                profileId = camera?.optNullableString("profileId"),
                captureMode = app?.optNullableString("captureMode") ?: json.optString("captureMode", "-"),
                controllerState = camera?.optNullableString("controllerState") ?: json.optString("controllerState", "-"),
                cameraReady = camera?.optBoolean("ready", false) ?: false,
                cameraRunning = camera?.optBoolean("running", false) ?: json.optBoolean("cameraRunning", false),
                previewRunning = camera?.optBoolean("previewRunning", false) ?: json.optBoolean("previewRunning", false),
                recordingActive = recording?.optBoolean("active", false) ?: false,
                recordingState = recording?.optString("state", "-") ?: "-",
                recordingFinalizing = recording?.optBoolean("finalizing", false) ?: false,
                isoManual = exposure?.optNullableBoolean("isoManual"),
                iso = exposure?.optNullableInt("iso") ?: camera?.optNullableInt("iso"),
                shutterManual = exposure?.optNullableBoolean("shutterManual"),
                shutterNs = exposure?.optNullableLong("shutterNs") ?: camera?.optNullableLong("shutterNs"),
                manualFocusEnabled = focus?.optNullableBoolean("manual") ?: camera?.optNullableBoolean("manualFocusEnabled"),
                focusDistance = focus?.optNullableDouble("distanceDiopters") ?: camera?.optNullableDouble("focusDistance"),
                whiteBalanceManual = whiteBalanceControls?.optNullableBoolean("manual"),
                whiteBalanceTemperature = whiteBalanceControls?.optNullableInt("temperature")
                    ?: legacyWhiteBalance?.optNullableInt("temperature"),
                whiteBalanceTint = whiteBalanceControls?.optNullableInt("tint")
                    ?: legacyWhiteBalance?.optNullableInt("tint"),
            )
        }
    }
}

data class CameraInfo(
    val id: String,
    val active: Boolean,
    val frontFacing: Boolean,
)

data class ProfileInfo(
    val id: String,
    val lensId: String,
    val cameraId: String,
    val name: String,
    val active: Boolean,
    val isDefault: Boolean,
    val autoGenerated: Boolean,
) {
    companion object {
        fun fromJson(json: JSONObject): ProfileInfo = ProfileInfo(
            id = json.optString("id", ""),
            lensId = json.optString("lensId", ""),
            cameraId = json.optString("cameraId", ""),
            name = json.optString("name", "Profile"),
            active = json.optBoolean("active", false),
            isDefault = json.optBoolean("default", false),
            autoGenerated = json.optBoolean("autoGenerated", false),
        )
    }
}

data class LensInfo(
    val id: String,
    val label: String,
    val buttonPrimaryLabel: String,
    val buttonSecondaryLabel: String?,
    val frontFacing: Boolean,
    val fallbackCameraId: String,
    val focalLengthMm: Double,
    val active: Boolean,
    val defaultProfileId: String?,
    val activeProfileId: String?,
    val profiles: List<ProfileInfo>,
) {
    companion object {
        fun fromJson(json: JSONObject): LensInfo = LensInfo(
            id = json.optString("id", ""),
            label = json.optString("label", ""),
            buttonPrimaryLabel = json.optString("buttonPrimaryLabel", ""),
            buttonSecondaryLabel = json.optNullableString("buttonSecondaryLabel"),
            frontFacing = json.optBoolean("frontFacing", false),
            fallbackCameraId = json.optString("fallbackCameraId", ""),
            focalLengthMm = json.optDouble("focalLengthMm", 0.0),
            active = json.optBoolean("active", false),
            defaultProfileId = json.optNullableString("defaultProfileId"),
            activeProfileId = json.optNullableString("activeProfileId"),
            profiles = json.optJSONArray("profiles").asObjectList(ProfileInfo::fromJson),
        )
    }
}

data class PreviewFrame(
    val jpegBytes: ByteArray,
    val streamId: String,
    val sequence: Long,
    val width: Int,
    val height: Int,
    val timestampMs: Long,
)

fun parsePreviewFrame(bytes: ByteArray): PreviewFrame? {
    if (bytes.size < 8) return null
    if (
        bytes[0] != 'M'.code.toByte() ||
        bytes[1] != 'C'.code.toByte() ||
        bytes[2] != 'P'.code.toByte() ||
        bytes[3] != 'V'.code.toByte()
    ) {
        return null
    }
    if (bytes[4].toInt() != 1 || bytes[5].toInt() != 1) {
        return null
    }

    val headerLength = ((bytes[6].toInt() and 0xff) shl 8) or (bytes[7].toInt() and 0xff)
    val headerStart = 8
    val jpegStart = headerStart + headerLength
    if (jpegStart >= bytes.size) return null

    val headerJson = bytes.decodeToString(headerStart, jpegStart)
    val header = JSONObject(headerJson)
    return PreviewFrame(
        jpegBytes = bytes.copyOfRange(jpegStart, bytes.size),
        streamId = header.optString("streamId", ""),
        sequence = header.optLong("sequence", 0L),
        width = header.optInt("width", 0),
        height = header.optInt("height", 0),
        timestampMs = header.optLong("timestampMs", 0L),
    )
}

internal fun authRequest(id: String, clientName: String, pairingDetails: PairingDetails): String {
    val params = JSONObject()
        .put("clientName", clientName)
        .put("protocolVersion", 1)
    if (!pairingDetails.pairingToken.isNullOrBlank()) {
        params.put("pairingToken", pairingDetails.pairingToken)
    } else {
        params.put("pairingCode", pairingDetails.pairingCode)
    }

    return JSONObject()
        .put("id", id)
        .put("method", "auth.hello")
        .put("params", params)
        .toString()
}

internal fun request(id: String, method: String, params: JSONObject? = null): String {
    val json = JSONObject()
        .put("id", id)
        .put("method", method)
    if (params != null) {
        json.put("params", params)
    }
    return json.toString()
}

internal fun parseAuthResult(json: JSONObject): AuthResult {
    return AuthResult(
        protocolVersion = json.optInt("protocolVersion", 1),
        authMode = json.optString("authMode", "-"),
        serverName = json.optString("serverName", "MotionCam"),
        clientName = json.optString("clientName", "-"),
        capabilities = json.optJSONArray("capabilities").asStringList(),
    )
}

private fun JSONArray?.asStringList(): List<String> {
    if (this == null) return emptyList()
    return buildList {
        for (index in 0 until length()) {
            add(optString(index))
        }
    }
}

internal fun parseCameraList(json: JSONObject): List<CameraInfo> =
    json.optJSONArray("cameras").asObjectList { camera ->
        CameraInfo(
            id = camera.optString("id", ""),
            active = camera.optBoolean("active", false),
            frontFacing = camera.optBoolean("frontFacing", false),
        )
    }

internal fun parseProfileList(json: JSONObject): List<ProfileInfo> =
    json.optJSONArray("profiles").asObjectList(ProfileInfo::fromJson)

internal fun parseLensList(json: JSONObject): List<LensInfo> =
    json.optJSONArray("lenses").asObjectList(LensInfo::fromJson)

private fun <T> JSONArray?.asObjectList(transform: (JSONObject) -> T): List<T> {
    if (this == null) return emptyList()
    return buildList {
        for (index in 0 until length()) {
            optJSONObject(index)?.let { add(transform(it)) }
        }
    }
}

private fun JSONObject.optNullableString(name: String): String? =
    if (has(name) && !isNull(name)) optString(name) else null

private fun JSONObject.optNullableInt(name: String): Int? =
    if (has(name) && !isNull(name)) optInt(name) else null

private fun JSONObject.optNullableLong(name: String): Long? =
    if (has(name) && !isNull(name)) optLong(name) else null

private fun JSONObject.optNullableDouble(name: String): Double? =
    if (has(name) && !isNull(name)) optDouble(name) else null

private fun JSONObject.optNullableBoolean(name: String): Boolean? =
    if (has(name) && !isNull(name)) optBoolean(name) else null
